### PR TITLE
add automations search

### PR DESCRIPTION
**Pull request by jpalmieri**
@PolRod

### CODE REVIEW

**Comment by PolRod** [comment]
It seems that you are rendering very similar layouts for automations, triggers, and macros. Maybe there would be a way to make that part of the code a bit more DRY? A part from that, :chocolate_bar: :star:

**Comment by jpalmieri** [comment]
@PolRod You're definitely right about that. In fact, there's absolutely no difference between the trigger and automation templates right now.

I thought about it, and it seems like the only way to make this DRYer is by modularizing each table row in the form, making an object for each search that tells which elements to include, and then rendering the elements based on the template selected. 

I'm not sure this is worth it at this point. Although doing it now may make it easier to scale.

Do you have any ideas?

**Comment by PolRod** [comment]
I like the idea of using modules, although it's true that it may be too much right now.another idea would be to have this generic template, and all of the searches that apply to it would change to that. Eg, instead of having `this.switchTo( $selectedOption.data('type') + '-search' );` you could replace `$selectedOption.data('type')`  with a variable, get the data-type first,and if it matches trigger or automation, set the variable to "generic". Right now it's not so bad that things are being repeated, but something to think about as it grows bigger!

**Comment by jpalmieri** [comment]
I'm gonna hold off on refactoring this right now.

Also, I think I'd rather keep the triggers and automations templates separate for now. Although they are identical, it's more semantic to have them as separate templates; we may want to add different fields to the templates in the future.

**Comment by jpalmieri** [comment]
@PolRod thanks for taking a look! I appreciate your comments!

**Pull request merged**
