### PR TITLE
[WE-4011] Migrate to Zendesk Apps v2 Framework

### PR DESCRIPTION
**Pull request by jpalmieri**
https://lumoslabs.atlassian.net/browse/WE-4011

cc @Liinal

### CODE REVIEW

**Comment by jpalmieri** [comment]
moving this to WIP, since I found some bugs...

**Comment by jpalmieri** [comment]
it's uploaded here, if you wanna peek: https://lumosity1375404535.zendesk.com/agent/apps/best-search

**Comment by jpalmieri** [comment]
ok @PolRod  and @Liinal, this is ready for a review. The recent version has been uploaded to https://lumosity1375404535.zendesk.com/agent/apps/best-search as well

**Review by PolRod — APPROVED** [review]

**Comment by Liinal** [comment]
It's all working great! seems to be working great! One thing I noticed is that the links for “Create new macro”, view, etc. use the old format for Zendesk - it still works so it’s not a big deal but you could change them to the new format:
https://lumosity.zendesk.com/agent/admin/macros/new
https://lumosity.zendesk.com/agent/admin/views/new
https://lumosity.zendesk.com/agent/admin/triggers/new
https://lumosity.zendesk.com/agent/admin/automations/new
New Dynamic Content doesn’t seem to have a distinct link though, so the old one works.

**Pull request merged**
